### PR TITLE
Switch Ganges platform to af repos

### PR DESCRIPTION
**Pull request by Haxk20**
This switches Ganges to afstamming projects.
As can be seen this project doesn't have the repos yet.
So this PR also comes with request to add the Ganges repos.
Thank you.

### CODE REVIEW

**Comment by MarijnS95** [comment]
What do you want as base branches to merge against? Seeing the branch names this is all against LOS 16, so Pie? I don't know how far along LOS 17 is already...

**Comment by Haxk20** [comment]
@MarijnS95 Pie branch please. Thank you.

**Comment by Haxk20** [comment]
I will start pushing to it tomorrow.

**Comment by MarijnS95** [comment]
Repos are created. I'm curious how much stuff is needed on top of what @ix5 already applied to the generic repos (common, sepolicy, etc). Be sure to check if there are commits from the other platforms to cherry-pick :)

**Comment by Haxk20** [comment]
@MarijnS95 There isnt much. Most of it is generic stuff.
If you could cherry pick this commit to android_hardware_qcom_audio please: [https://android.googlesource.com/platform/hardware/qcom/audio/+/eeecf8a399080598e5290d3356b0ad557bd0ccbd](https://android.googlesource.com/platform/hardware/qcom/audio/+/eeecf8a399080598e5290d3356b0ad557bd0ccbd)

**Comment by Haxk20** [comment]
@MarijnS95 BTW if i may ask. Where did the name afstamming came from ?

**Comment by MarijnS95** [comment]
That commit is already on the afstamming branch. I just deleted all the 160something others that are irrelevant.

I don't exactly know where the name came from. @ix5 came up with it and it's dutch for descendant, or lineage :)

**Comment by Haxk20** [comment]
@MarijnS95 HAHAHA very cool. @ix5 Very good job on the name

**Comment by Haxk20** [comment]
@MarijnS95 Can this and the PRs in ganges get merged. They are ready to build and will work like that. Only thing is missing is resolution for bootanimation and charging led fix.

**Comment by Haxk20** [comment]
BTW Ganges is almost ready. Only fingerprint is not working at this moment

**Comment by MarijnS95** [comment]
@Haxk20 I'm not able to review any of it so will leave that to @ix5. I don't see the use of these source/setup scripts yet, since we will not bundle blobs that way _anyway_ - it's where we have odm images for.

Anyway, we need to keep dualsim variants in there. I know it's easy to ditch and happens commonly (and there is a flashable zip to do the update), but I want to be able to build for the right device directly.

**Comment by ix5** [comment]
@Haxk20 if you're really interested, I can add you as a collaborator here.
I don't have time to maintain this, it was mostly a silly idea between Marijn and me to "see whether we can get a dirty Lineage port up quickly".

And yes, I felt pretty damn clever choosing the name ;)

**Comment by Haxk20** [comment]
@ix5 Yes please. Being a collaborator here would be great since i would not have to wait for my changes to get merged.
Thank you.
I mean the idea is great. Quick port of custom ROM is always welcome in the community. Mostly for such a new device as mine.

And really the name once marijn explained was awesome.

**Comment by ix5** [comment]
You're in. But please keep the changes to a minimum. No l33t h4x and rices, only what is absolutely needed to get LineageOS up.
Take the kagura/tone repos as an example, and don't add much more.

**Comment by Haxk20** [comment]
HAHAHAHAHA. OK I will keep it to minimum. I will go full development on my personal repos.
And thanks.

**Comment by Haxk20** [comment]
@ix5 But could you merge the PRs i posted to Kirin, Mermaid, Ganges ? I dont have the ability to do so.

**Comment by Haxk20** [comment]
@ix5 BTW the manifest has some issues still. Will fix them tomorrow. Im now building AOSP10 and will make a quick LineageOS17 port out of it most likely.

**Pull request merged**
