### PR TITLE
sdm845_gps does not contain af-lineage-16.0 branch

### PR DESCRIPTION
**Pull request by Haxk20**
As the commit says there is no reason to have our own copy of the project when its copy of master.

### CODE REVIEW

**Comment by Haxk20** [comment]
@ix5 Please review this just to be sure

**Comment by ix5** [comment]
We need the stuff from `repo_update.sh` applied here because we're not using `repo_update.sh` with lineage sources.

**Comment by ix5** [comment]
You can push it youself if you want.

**Comment by Haxk20** [comment]
@ix5 Ahh i see so it would be best just to create the branch and close this PR.

**Pull request closed without merging**
